services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION:eu-north-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT_URL=http://localhost:4566
      #- AWS_PROFILE=default
    ports:
      - "4566:4566"
    volumes:
      - "./localstack:/var/lib/localstack"